### ISSUE TITLE
Missing Site Titles Causes Favorite to Be Labeled "Wiki"

### ISSUE THREAD

**Issue by Poikilos** [requarks/wiki-site-v2#12]
There is no unique title for certain pages, so after adding a bookmark, the bookmark is labeled "Wiki" for:
- <https://docs-legacy.requarks.io/wiki/user-guide/markdown-syntax>
- Whether this is the only page titled "Wiki" or there are more is unknown.

**Comment by Poikilos** [comment]
Uhh, do you understand what is happening here? The site title is not set. I am not asking you to change the default, I'm asking you to add a title so that when people add your page to favorites or add a shortcut to it some other way, or want to be able to find the tab again, the name is something descriptive.

**Comment by NGPixel** [comment]
The link you pointed to in your original comment is for the Wiki.js v1 site, which was archived a long time ago. So unless this is not the site you're referring to, this issue is now irrelevant.

**Comment by Poikilos** [comment]
Ok it is resolved. I was confused by "closed this as not planned".
